<?php

namespace ContainerI2oqHDv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_OzCxPBEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.OzCxPBE' shared service.
     *
     * @return \Symfony\Component\Security\Core\Security
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\DashboardController::index()": the $security argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Security".');
    }
}
