<?php

namespace ContainerI2oqHDv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVolunteerControllerexportCsvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WyVX2u3.App\Controller\VolunteerController::exportCsv()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WyVX2u3.App\\Controller\\VolunteerController::exportCsv()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'volunteerRepository' => ['privates', 'App\\Repository\\VolunteerRepository', 'getVolunteerRepositoryService', true],
        ], [
            'volunteerRepository' => 'App\\Repository\\VolunteerRepository',
        ]))->withContext('App\\Controller\\VolunteerController::exportCsv()', $container);
    }
}
