<?php

namespace ContainerKWZfS2R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_LmhawWlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.lmhawWl' shared service.
     *
     * @return \Symfony\Component\Security\Core\Security
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ServiceController::attend()": the $security argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Security".');
    }
}
