<?php

namespace ContainerKWZfS2R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllerlistServicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GRBUYSM.App\Controller\ServiceController::listServices()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GRBUYSM.App\\Controller\\ServiceController::listServices()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
            'security' => ['privates', '.errored.Zoq0Nlj', NULL, 'Cannot determine controller argument for "App\\Controller\\ServiceController::listServices()": the $security argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Security".'],
        ], [
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
            'security' => '?',
        ]))->withContext('App\\Controller\\ServiceController::listServices()', $container);
    }
}
