<?php

namespace ContainerKWZfS2R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllerattendService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UMF9I6e.App\Controller\ServiceController::attend()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UMF9I6e.App\\Controller\\ServiceController::attend()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'service' => ['privates', 'App\\Entity\\Service', 'getServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', '.errored.lmhawWl', NULL, 'Cannot determine controller argument for "App\\Controller\\ServiceController::attend()": the $security argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Security".'],
        ], [
            'service' => 'App\\Entity\\Service',
            'entityManager' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\ServiceController::attend()', $container);
    }
}
