<?php

namespace ContainerKWZfS2R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVolunteerControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T9SYb7Z.App\Controller\VolunteerController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T9SYb7Z.App\\Controller\\VolunteerController::list()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'volunteerRepository' => ['privates', 'App\\Repository\\VolunteerRepository', 'getVolunteerRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'volunteerRepository' => 'App\\Repository\\VolunteerRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\VolunteerController::list()', $container);
    }
}
