<?php

namespace ContainerPwaqcf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WyVX2u3.App\Controller\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WyVX2u3.App\\Controller\\DashboardController::index()'] = ($container->privates['.service_locator.WyVX2u3'] ?? $container->load('get_ServiceLocator_WyVX2u3Service'))->withContext('App\\Controller\\DashboardController::index()', $container);
    }
}
