services:
  # Base de datos (MySQL)
  database:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_voluntarios
    ports:
      - "3306:3306"
    networks:
      - symfony_net

# Interfaz gráfica para la base de datos
  phpmyadmin:
    image: phpmyadmin
    container_name: symfony_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: symfony_db      # El nombre del servicio de base de datos
      MYSQL_ROOT_PASSWORD: root  # La contraseña que ya definiste
    networks:
      - symfony_net
    depends_on:
      - database

  # El motor de PHP
  php:
    build: .
    container_name: symfony_php
    volumes:
      - .:/var/www/symfony
    depends_on:
      - database
    networks:
      - symfony_net

  # El servidor web (Nginx)
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony_net

# Definición de la red aislada
networks:
  symfony_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.150.0/24