when@dev:
    web_profiler_wdt:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.php'
        prefix: /_wdt

    web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.php'
        prefix: /_profiler

    app_auto_login:
        path: /auto-login/{id}
        controller: App\Controller\SecurityController::autoLogin
        methods: [GET]
