<?php

namespace ContainerXA2Kvcr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSampleDataCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\CreateSampleDataCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\CreateSampleDataCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-sample-data', [], 'Crear datos de ejemplo para voluntarios', false, #[\Closure(name: 'App\\Command\\CreateSampleDataCommand')] fn (): \App\Command\CreateSampleDataCommand => ($container->privates['App\\Command\\CreateSampleDataCommand'] ?? $container->load('getCreateSampleDataCommandService')));
    }
}
