<?php

namespace ContainerXA2Kvcr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVolunteerTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\VolunteerType' shared autowired service.
     *
     * @return \App\Form\VolunteerType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\VolunteerType'] = new \App\Form\VolunteerType();
    }
}
