<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260427113236 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TEMPORARY TABLE __temp__maestro_material AS SELECT id, assigned_vehicle_id, name, category, nature, stock, safety_stock, image_path, barcode, description, batch_number, units_per_package, sub_family, expiration_date, supplier, unit_price, iva, total_price, discount_percentage, margin_percentage, serial_number, network_id, phone_number, brand_model, frequency_band, device_type, purchase_date, warranty_date, has_charger, has_clip, has_microphone, operational_status, battery_status FROM maestro_material');
        $this->addSql('DROP TABLE maestro_material');
        $this->addSql('CREATE TABLE maestro_material (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, assigned_vehicle_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(50) DEFAULT NULL, nature VARCHAR(20) DEFAULT \'CONSUMIBLE\' NOT NULL, stock INTEGER DEFAULT 0 NOT NULL, safety_stock INTEGER DEFAULT 0 NOT NULL, image_path VARCHAR(255) DEFAULT NULL, barcode VARCHAR(255) DEFAULT NULL, description CLOB DEFAULT NULL, batch_number VARCHAR(100) DEFAULT NULL, units_per_package INTEGER DEFAULT NULL, sub_family VARCHAR(100) DEFAULT NULL, expiration_date DATETIME DEFAULT NULL, supplier VARCHAR(255) DEFAULT NULL, unit_price NUMERIC(10, 2) DEFAULT \'0\' NOT NULL, iva NUMERIC(5, 2) DEFAULT \'21\' NOT NULL, total_price NUMERIC(10, 2) DEFAULT NULL, discount_percentage NUMERIC(5, 2) DEFAULT NULL, margin_percentage NUMERIC(5, 2) DEFAULT NULL, serial_number VARCHAR(255) DEFAULT NULL, network_id VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(50) DEFAULT NULL, brand_model VARCHAR(255) DEFAULT NULL, frequency_band VARCHAR(50) DEFAULT NULL, device_type VARCHAR(50) DEFAULT NULL, purchase_date DATETIME DEFAULT NULL, warranty_date DATETIME DEFAULT NULL, has_charger BOOLEAN DEFAULT 0 NOT NULL, has_clip BOOLEAN DEFAULT 0 NOT NULL, has_microphone BOOLEAN DEFAULT 0 NOT NULL, operational_status VARCHAR(50) DEFAULT NULL, battery_status VARCHAR(50) DEFAULT NULL, CONSTRAINT FK_3DACC1916CF274A0 FOREIGN KEY (assigned_vehicle_id) REFERENCES vehicle (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO maestro_material (id, assigned_vehicle_id, name, category, nature, stock, safety_stock, image_path, barcode, description, batch_number, units_per_package, sub_family, expiration_date, supplier, unit_price, iva, total_price, discount_percentage, margin_percentage, serial_number, network_id, phone_number, brand_model, frequency_band, device_type, purchase_date, warranty_date, has_charger, has_clip, has_microphone, operational_status, battery_status) SELECT id, assigned_vehicle_id, name, category, nature, stock, safety_stock, image_path, barcode, description, batch_number, units_per_package, sub_family, expiration_date, supplier, unit_price, iva, total_price, discount_percentage, margin_percentage, serial_number, network_id, phone_number, brand_model, frequency_band, device_type, purchase_date, warranty_date, has_charger, has_clip, has_microphone, operational_status, battery_status FROM __temp__maestro_material');
        $this->addSql('DROP TABLE __temp__maestro_material');
        $this->addSql('CREATE INDEX IDX_3DACC1916CF274A0 ON maestro_material (assigned_vehicle_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3DACC19134128B91 ON maestro_material (network_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3DACC191D948EE2 ON maestro_material (serial_number)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__material_unit AS SELECT id, material_id, location_id, template_id, kit_location_id, serial_number, collective_number, last_used_at, is_in_maintenance, ptt_status, cover_status, battery_status, alias, network_id, phone_number, operational_status, purchase_price, discount_pct, supplier, iva, margin_percentage, purchase_date, warranty_date, has_charger, has_clip, has_microphone, brand_model FROM material_unit');
        $this->addSql('DROP TABLE material_unit');
        $this->addSql('CREATE TABLE material_unit (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, material_id INTEGER NOT NULL, location_id INTEGER DEFAULT NULL, template_id INTEGER DEFAULT NULL, kit_location_id INTEGER DEFAULT NULL, serial_number VARCHAR(255) DEFAULT NULL, collective_number VARCHAR(50) DEFAULT NULL, last_used_at DATETIME DEFAULT NULL, is_in_maintenance BOOLEAN DEFAULT 0 NOT NULL, ptt_status VARCHAR(50) DEFAULT NULL, cover_status VARCHAR(50) DEFAULT NULL, battery_status VARCHAR(50) DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL, network_id VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(50) DEFAULT NULL, operational_status VARCHAR(50) DEFAULT NULL, purchase_price NUMERIC(10, 2) DEFAULT NULL, discount_pct NUMERIC(5, 2) DEFAULT NULL, supplier VARCHAR(255) DEFAULT NULL, iva NUMERIC(5, 2) DEFAULT \'21\' NOT NULL, margin_percentage NUMERIC(5, 2) DEFAULT NULL, purchase_date DATETIME DEFAULT NULL, warranty_date DATETIME DEFAULT NULL, has_charger BOOLEAN DEFAULT 0 NOT NULL, has_clip BOOLEAN DEFAULT 0 NOT NULL, has_microphone BOOLEAN DEFAULT 0 NOT NULL, brand_model VARCHAR(255) DEFAULT NULL, CONSTRAINT FK_88D36166E308AC6F FOREIGN KEY (material_id) REFERENCES maestro_material (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_88D3616664D218E FOREIGN KEY (location_id) REFERENCES location (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_88D361665DA0FB8 FOREIGN KEY (template_id) REFERENCES kit_template (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_88D3616630FAD39E FOREIGN KEY (kit_location_id) REFERENCES location (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO material_unit (id, material_id, location_id, template_id, kit_location_id, serial_number, collective_number, last_used_at, is_in_maintenance, ptt_status, cover_status, battery_status, alias, network_id, phone_number, operational_status, purchase_price, discount_pct, supplier, iva, margin_percentage, purchase_date, warranty_date, has_charger, has_clip, has_microphone, brand_model) SELECT id, material_id, location_id, template_id, kit_location_id, serial_number, collective_number, last_used_at, is_in_maintenance, ptt_status, cover_status, battery_status, alias, network_id, phone_number, operational_status, purchase_price, discount_pct, supplier, iva, margin_percentage, purchase_date, warranty_date, has_charger, has_clip, has_microphone, brand_model FROM __temp__material_unit');
        $this->addSql('DROP TABLE __temp__material_unit');
        $this->addSql('CREATE INDEX IDX_88D3616630FAD39E ON material_unit (kit_location_id)');
        $this->addSql('CREATE INDEX IDX_88D361665DA0FB8 ON material_unit (template_id)');
        $this->addSql('CREATE INDEX IDX_88D3616664D218E ON material_unit (location_id)');
        $this->addSql('CREATE INDEX IDX_88D36166E308AC6F ON material_unit (material_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88D36166E16C6B94 ON material_unit (alias)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TEMPORARY TABLE __temp__maestro_material AS SELECT id, assigned_vehicle_id, name, category, nature, stock, safety_stock, image_path, barcode, description, batch_number, units_per_package, sub_family, expiration_date, supplier, unit_price, iva, total_price, discount_percentage, margin_percentage, serial_number, network_id, phone_number, brand_model, frequency_band, device_type, purchase_date, warranty_date, has_charger, has_clip, has_microphone, operational_status, battery_status FROM maestro_material');
        $this->addSql('DROP TABLE maestro_material');
        $this->addSql('CREATE TABLE maestro_material (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, assigned_vehicle_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(50) DEFAULT NULL, nature VARCHAR(20) DEFAULT \'CONSUMIBLE\' NOT NULL, stock INTEGER DEFAULT 0 NOT NULL, safety_stock INTEGER DEFAULT 0 NOT NULL, image_path VARCHAR(255) DEFAULT NULL, barcode VARCHAR(255) DEFAULT NULL, description CLOB DEFAULT NULL, batch_number VARCHAR(100) DEFAULT NULL, units_per_package INTEGER DEFAULT NULL, sub_family VARCHAR(100) DEFAULT NULL, expiration_date DATE DEFAULT NULL --(DC2Type:date_immutable)
        , supplier VARCHAR(255) DEFAULT NULL, unit_price NUMERIC(10, 2) DEFAULT \'0\' NOT NULL, iva NUMERIC(5, 2) DEFAULT \'21\' NOT NULL, total_price NUMERIC(10, 2) DEFAULT NULL, discount_percentage NUMERIC(5, 2) DEFAULT NULL, margin_percentage NUMERIC(5, 2) DEFAULT NULL, serial_number VARCHAR(255) DEFAULT NULL, network_id VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(50) DEFAULT NULL, brand_model VARCHAR(255) DEFAULT NULL, frequency_band VARCHAR(50) DEFAULT NULL, device_type VARCHAR(50) DEFAULT NULL, purchase_date DATETIME DEFAULT NULL, warranty_date DATETIME DEFAULT NULL, has_charger BOOLEAN DEFAULT 0 NOT NULL, has_clip BOOLEAN DEFAULT 0 NOT NULL, has_microphone BOOLEAN DEFAULT 0 NOT NULL, operational_status VARCHAR(50) DEFAULT NULL, battery_status VARCHAR(50) DEFAULT NULL, CONSTRAINT FK_3DACC1916CF274A0 FOREIGN KEY (assigned_vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO maestro_material (id, assigned_vehicle_id, name, category, nature, stock, safety_stock, image_path, barcode, description, batch_number, units_per_package, sub_family, expiration_date, supplier, unit_price, iva, total_price, discount_percentage, margin_percentage, serial_number, network_id, phone_number, brand_model, frequency_band, device_type, purchase_date, warranty_date, has_charger, has_clip, has_microphone, operational_status, battery_status) SELECT id, assigned_vehicle_id, name, category, nature, stock, safety_stock, image_path, barcode, description, batch_number, units_per_package, sub_family, expiration_date, supplier, unit_price, iva, total_price, discount_percentage, margin_percentage, serial_number, network_id, phone_number, brand_model, frequency_band, device_type, purchase_date, warranty_date, has_charger, has_clip, has_microphone, operational_status, battery_status FROM __temp__maestro_material');
        $this->addSql('DROP TABLE __temp__maestro_material');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3DACC191D948EE2 ON maestro_material (serial_number)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3DACC19134128B91 ON maestro_material (network_id)');
        $this->addSql('CREATE INDEX IDX_3DACC1916CF274A0 ON maestro_material (assigned_vehicle_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__material_unit AS SELECT id, material_id, location_id, template_id, kit_location_id, serial_number, collective_number, last_used_at, is_in_maintenance, ptt_status, cover_status, battery_status, alias, network_id, phone_number, operational_status, purchase_price, discount_pct, supplier, iva, margin_percentage, purchase_date, warranty_date, has_charger, has_clip, has_microphone, brand_model FROM material_unit');
        $this->addSql('DROP TABLE material_unit');
        $this->addSql('CREATE TABLE material_unit (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, material_id INTEGER NOT NULL, location_id INTEGER DEFAULT NULL, template_id INTEGER DEFAULT NULL, kit_location_id INTEGER DEFAULT NULL, serial_number VARCHAR(255) DEFAULT NULL, collective_number VARCHAR(50) DEFAULT NULL, last_used_at DATETIME DEFAULT NULL --(DC2Type:datetime_immutable)
        , is_in_maintenance BOOLEAN DEFAULT 0 NOT NULL, ptt_status VARCHAR(50) DEFAULT NULL, cover_status VARCHAR(50) DEFAULT NULL, battery_status VARCHAR(50) DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL, network_id VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(50) DEFAULT NULL, operational_status VARCHAR(50) DEFAULT NULL, purchase_price NUMERIC(10, 2) DEFAULT NULL, discount_pct NUMERIC(5, 2) DEFAULT NULL, supplier VARCHAR(255) DEFAULT NULL, iva NUMERIC(5, 2) DEFAULT \'21\' NOT NULL, margin_percentage NUMERIC(5, 2) DEFAULT NULL, purchase_date DATETIME DEFAULT NULL, warranty_date DATETIME DEFAULT NULL, has_charger BOOLEAN DEFAULT 0 NOT NULL, has_clip BOOLEAN DEFAULT 0 NOT NULL, has_microphone BOOLEAN DEFAULT 0 NOT NULL, brand_model VARCHAR(255) DEFAULT NULL, CONSTRAINT FK_88D36166E308AC6F FOREIGN KEY (material_id) REFERENCES maestro_material (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_88D3616664D218E FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_88D361665DA0FB8 FOREIGN KEY (template_id) REFERENCES kit_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_88D3616630FAD39E FOREIGN KEY (kit_location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO material_unit (id, material_id, location_id, template_id, kit_location_id, serial_number, collective_number, last_used_at, is_in_maintenance, ptt_status, cover_status, battery_status, alias, network_id, phone_number, operational_status, purchase_price, discount_pct, supplier, iva, margin_percentage, purchase_date, warranty_date, has_charger, has_clip, has_microphone, brand_model) SELECT id, material_id, location_id, template_id, kit_location_id, serial_number, collective_number, last_used_at, is_in_maintenance, ptt_status, cover_status, battery_status, alias, network_id, phone_number, operational_status, purchase_price, discount_pct, supplier, iva, margin_percentage, purchase_date, warranty_date, has_charger, has_clip, has_microphone, brand_model FROM __temp__material_unit');
        $this->addSql('DROP TABLE __temp__material_unit');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88D36166E16C6B94 ON material_unit (alias)');
        $this->addSql('CREATE INDEX IDX_88D36166E308AC6F ON material_unit (material_id)');
        $this->addSql('CREATE INDEX IDX_88D3616664D218E ON material_unit (location_id)');
        $this->addSql('CREATE INDEX IDX_88D361665DA0FB8 ON material_unit (template_id)');
        $this->addSql('CREATE INDEX IDX_88D3616630FAD39E ON material_unit (kit_location_id)');
    }
}
