<?php

namespace ContainerQbrd0iU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHashPasswordCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\HashPasswordCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\HashPasswordCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('HashPasswordCommand', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\HashPasswordCommand')] fn (): \App\Command\HashPasswordCommand => ($container->privates['App\\Command\\HashPasswordCommand'] ?? $container->load('getHashPasswordCommandService')));
    }
}
