<?php

namespace ContainerQbrd0iU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHashPasswordCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\HashPasswordCommand' shared autowired service.
     *
     * @return \App\Command\HashPasswordCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\HashPasswordCommand'] = $instance = new \App\Command\HashPasswordCommand();

        $instance->setName('HashPasswordCommand');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
