<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXA2Kvcr\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXA2Kvcr/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXA2Kvcr.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXA2Kvcr\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXA2Kvcr\App_KernelProdContainer([
    'container.build_hash' => 'XA2Kvcr',
    'container.build_id' => '43c34c62',
    'container.build_time' => 1751362408,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXA2Kvcr');
