<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGfMxL7x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGfMxL7x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGfMxL7x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGfMxL7x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGfMxL7x\App_KernelDevDebugContainer([
    'container.build_hash' => 'GfMxL7x',
    'container.build_id' => '3deb7641',
    'container.build_time' => 1752174370,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGfMxL7x');
