<?php

namespace ContainerJNyZYD5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVolunteerRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\VolunteerRepository' shared autowired service.
     *
     * @return \App\Repository\VolunteerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\VolunteerRepository'] = new \App\Repository\VolunteerRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
