<?php

namespace ContainerJNyZYD5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVolunteerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Entity\Volunteer' shared autowired service.
     *
     * @return \App\Entity\Volunteer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Entity\\Volunteer'] = new \App\Entity\Volunteer();
    }
}
