controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

admin_import_hours:
    path: /admin/import-hours
    controller: App\Controller\Admin\ImportController::index
