<?php

namespace ContainerIkH74Uj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GUwuf70Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gUwuf70' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gUwuf70'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.MkkPcrP.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\ServiceController::listServices' => ['privates', '.service_locator..wKp6bH.App\\Controller\\ServiceController::listServices()', 'getServiceControllerlistServicesService', true],
            'App\\Controller\\ServiceController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\ServiceController::new()', 'getServiceControllernewService', true],
            'App\\Controller\\ServiceController::show' => ['privates', '.service_locator.LXavkRP.App\\Controller\\ServiceController::show()', 'getServiceControllershowService', true],
            'App\\Controller\\ServiceController::edit' => ['privates', '.service_locator.7gwO4lR.App\\Controller\\ServiceController::edit()', 'getServiceControllereditService', true],
            'App\\Controller\\ServiceController::attend' => ['privates', '.service_locator.UMF9I6e.App\\Controller\\ServiceController::attend()', 'getServiceControllerattendService', true],
            'App\\Controller\\ServiceController::unattend' => ['privates', '.service_locator.HrZ3P21.App\\Controller\\ServiceController::unattend()', 'getServiceControllerunattendService', true],
            'App\\Controller\\VolunteerController::list' => ['privates', '.service_locator.T9SYb7Z.App\\Controller\\VolunteerController::list()', 'getVolunteerControllerlistService', true],
            'App\\Controller\\VolunteerController::new' => ['privates', '.service_locator.rg_k2Ip.App\\Controller\\VolunteerController::new()', 'getVolunteerControllernewService', true],
            'App\\Controller\\VolunteerController::registration' => ['privates', '.service_locator.rg_k2Ip.App\\Controller\\VolunteerController::registration()', 'getVolunteerControllerregistrationService', true],
            'App\\Controller\\VolunteerController::edit' => ['privates', '.service_locator.5D8TDWv.App\\Controller\\VolunteerController::edit()', 'getVolunteerControllereditService', true],
            'App\\Controller\\VolunteerController::exportCsv' => ['privates', '.service_locator.WyVX2u3.App\\Controller\\VolunteerController::exportCsv()', 'getVolunteerControllerexportCsvService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.MkkPcrP.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\ServiceController:listServices' => ['privates', '.service_locator..wKp6bH.App\\Controller\\ServiceController::listServices()', 'getServiceControllerlistServicesService', true],
            'App\\Controller\\ServiceController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\ServiceController::new()', 'getServiceControllernewService', true],
            'App\\Controller\\ServiceController:show' => ['privates', '.service_locator.LXavkRP.App\\Controller\\ServiceController::show()', 'getServiceControllershowService', true],
            'App\\Controller\\ServiceController:edit' => ['privates', '.service_locator.7gwO4lR.App\\Controller\\ServiceController::edit()', 'getServiceControllereditService', true],
            'App\\Controller\\ServiceController:attend' => ['privates', '.service_locator.UMF9I6e.App\\Controller\\ServiceController::attend()', 'getServiceControllerattendService', true],
            'App\\Controller\\ServiceController:unattend' => ['privates', '.service_locator.HrZ3P21.App\\Controller\\ServiceController::unattend()', 'getServiceControllerunattendService', true],
            'App\\Controller\\VolunteerController:list' => ['privates', '.service_locator.T9SYb7Z.App\\Controller\\VolunteerController::list()', 'getVolunteerControllerlistService', true],
            'App\\Controller\\VolunteerController:new' => ['privates', '.service_locator.rg_k2Ip.App\\Controller\\VolunteerController::new()', 'getVolunteerControllernewService', true],
            'App\\Controller\\VolunteerController:registration' => ['privates', '.service_locator.rg_k2Ip.App\\Controller\\VolunteerController::registration()', 'getVolunteerControllerregistrationService', true],
            'App\\Controller\\VolunteerController:edit' => ['privates', '.service_locator.5D8TDWv.App\\Controller\\VolunteerController::edit()', 'getVolunteerControllereditService', true],
            'App\\Controller\\VolunteerController:exportCsv' => ['privates', '.service_locator.WyVX2u3.App\\Controller\\VolunteerController::exportCsv()', 'getVolunteerControllerexportCsvService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\ServiceController::listServices' => '?',
            'App\\Controller\\ServiceController::new' => '?',
            'App\\Controller\\ServiceController::show' => '?',
            'App\\Controller\\ServiceController::edit' => '?',
            'App\\Controller\\ServiceController::attend' => '?',
            'App\\Controller\\ServiceController::unattend' => '?',
            'App\\Controller\\VolunteerController::list' => '?',
            'App\\Controller\\VolunteerController::new' => '?',
            'App\\Controller\\VolunteerController::registration' => '?',
            'App\\Controller\\VolunteerController::edit' => '?',
            'App\\Controller\\VolunteerController::exportCsv' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\ServiceController:listServices' => '?',
            'App\\Controller\\ServiceController:new' => '?',
            'App\\Controller\\ServiceController:show' => '?',
            'App\\Controller\\ServiceController:edit' => '?',
            'App\\Controller\\ServiceController:attend' => '?',
            'App\\Controller\\ServiceController:unattend' => '?',
            'App\\Controller\\VolunteerController:list' => '?',
            'App\\Controller\\VolunteerController:new' => '?',
            'App\\Controller\\VolunteerController:registration' => '?',
            'App\\Controller\\VolunteerController:edit' => '?',
            'App\\Controller\\VolunteerController:exportCsv' => '?',
        ]);
    }
}
