<?php

namespace Container2a3izvF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.WyVX2u3.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\VolunteerController::list' => ['privates', '.service_locator.WyVX2u3.App\\Controller\\VolunteerController::list()', 'getVolunteerControllerlistService', true],
            'App\\Controller\\VolunteerController::new' => ['privates', '.service_locator.A84gqGd.App\\Controller\\VolunteerController::new()', 'getVolunteerControllernewService', true],
            'App\\Controller\\VolunteerController::registration' => ['privates', '.service_locator.A84gqGd.App\\Controller\\VolunteerController::registration()', 'getVolunteerControllerregistrationService', true],
            'App\\Controller\\VolunteerController::exportCsv' => ['privates', '.service_locator.WyVX2u3.App\\Controller\\VolunteerController::exportCsv()', 'getVolunteerControllerexportCsvService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.WyVX2u3.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\VolunteerController:list' => ['privates', '.service_locator.WyVX2u3.App\\Controller\\VolunteerController::list()', 'getVolunteerControllerlistService', true],
            'App\\Controller\\VolunteerController:new' => ['privates', '.service_locator.A84gqGd.App\\Controller\\VolunteerController::new()', 'getVolunteerControllernewService', true],
            'App\\Controller\\VolunteerController:registration' => ['privates', '.service_locator.A84gqGd.App\\Controller\\VolunteerController::registration()', 'getVolunteerControllerregistrationService', true],
            'App\\Controller\\VolunteerController:exportCsv' => ['privates', '.service_locator.WyVX2u3.App\\Controller\\VolunteerController::exportCsv()', 'getVolunteerControllerexportCsvService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\VolunteerController::list' => '?',
            'App\\Controller\\VolunteerController::new' => '?',
            'App\\Controller\\VolunteerController::registration' => '?',
            'App\\Controller\\VolunteerController::exportCsv' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\VolunteerController:list' => '?',
            'App\\Controller\\VolunteerController:new' => '?',
            'App\\Controller\\VolunteerController:registration' => '?',
            'App\\Controller\\VolunteerController:exportCsv' => '?',
        ]));
    }
}
