<?php

namespace Container2a3izvF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSampleDataCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CreateSampleDataCommand' shared autowired service.
     *
     * @return \App\Command\CreateSampleDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CreateSampleDataCommand'] = $instance = new \App\Command\CreateSampleDataCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:create-sample-data');
        $instance->setDescription('Crear datos de ejemplo para voluntarios');

        return $instance;
    }
}
