<?php

namespace Container2a3izvF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVolunteerControllerregistrationService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.A84gqGd.App\Controller\VolunteerController::registration()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A84gqGd.App\\Controller\\VolunteerController::registration()'] = ($container->privates['.service_locator.A84gqGd'] ?? $container->load('get_ServiceLocator_A84gqGdService'))->withContext('App\\Controller\\VolunteerController::registration()', $container);
    }
}
