knp_paginator:
    page_range: 2           # number of links to show in the pagination menu (e.g. 2 is then current page - 2, current page + 2)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when joining
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:
        pagination: '@KnpPaginator/Pagination/tailwindcss_pagination.html.twig' # O el que uses (bootstrap_v5_pagination.html.twig, etc.)
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'