<?php

namespace ContainerG2EbToo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllerlistServicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wd5sNgM.App\Controller\ServiceController::listServices()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wd5sNgM.App\\Controller\\ServiceController::listServices()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
            'security' => '?',
        ]))->withContext('App\\Controller\\ServiceController::listServices()', $container);
    }
}
