<?php

namespace ContainerG2EbToo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllerunattendService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.86Kiu4b.App\Controller\ServiceController::unattend()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.86Kiu4b.App\\Controller\\ServiceController::unattend()'] = ($container->privates['.service_locator.86Kiu4b'] ?? $container->load('get_ServiceLocator_86Kiu4bService'))->withContext('App\\Controller\\ServiceController::unattend()', $container);
    }
}
