<?php

namespace ContainerG2EbToo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LXavkRP.App\Controller\ServiceController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LXavkRP.App\\Controller\\ServiceController::show()'] = ($container->privates['.service_locator.LXavkRP'] ?? $container->load('get_ServiceLocator_LXavkRPService'))->withContext('App\\Controller\\ServiceController::show()', $container);
    }
}
