<?php

namespace ContainerG2EbToo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceControllerattendService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.86Kiu4b.App\Controller\ServiceController::attend()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.86Kiu4b'] ?? $container->load('get_ServiceLocator_86Kiu4bService'));

        if (isset($container->privates['.service_locator.86Kiu4b.App\\Controller\\ServiceController::attend()'])) {
            return $container->privates['.service_locator.86Kiu4b.App\\Controller\\ServiceController::attend()'];
        }

        return $container->privates['.service_locator.86Kiu4b.App\\Controller\\ServiceController::attend()'] = $a->withContext('App\\Controller\\ServiceController::attend()', $container);
    }
}
