<?php

namespace ContainerG2EbToo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVolunteerControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5D8TDWv.App\Controller\VolunteerController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5D8TDWv.App\\Controller\\VolunteerController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'volunteer' => ['privates', 'App\\Entity\\Volunteer', 'getVolunteerService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'volunteer' => 'App\\Entity\\Volunteer',
            'entityManager' => '?',
            'userPasswordHasher' => '?',
        ]))->withContext('App\\Controller\\VolunteerController::edit()', $container);
    }
}
