<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIkH74Uj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIkH74Uj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIkH74Uj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIkH74Uj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIkH74Uj\App_KernelDevDebugContainer([
    'container.build_hash' => 'IkH74Uj',
    'container.build_id' => 'f371d70c',
    'container.build_time' => 1752663325,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIkH74Uj');
