<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Volunteer extends \App\Entity\Volunteer implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null, 16],
        "\0".parent::class."\0".'allergies' => [parent::class, 'allergies', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'contactPerson1' => [parent::class, 'contactPerson1', null, 16],
        "\0".parent::class."\0".'contactPerson2' => [parent::class, 'contactPerson2', null, 16],
        "\0".parent::class."\0".'contactPhone1' => [parent::class, 'contactPhone1', null, 16],
        "\0".parent::class."\0".'contactPhone2' => [parent::class, 'contactPhone2', null, 16],
        "\0".parent::class."\0".'dateOfBirth' => [parent::class, 'dateOfBirth', null, 16],
        "\0".parent::class."\0".'dni' => [parent::class, 'dni', null, 16],
        "\0".parent::class."\0".'drivingLicenseExpiryDate' => [parent::class, 'drivingLicenseExpiryDate', null, 16],
        "\0".parent::class."\0".'drivingLicenses' => [parent::class, 'drivingLicenses', null, 16],
        "\0".parent::class."\0".'employmentStatus' => [parent::class, 'employmentStatus', null, 16],
        "\0".parent::class."\0".'hasVolunteeredBefore' => [parent::class, 'hasVolunteeredBefore', null, 16],
        "\0".parent::class."\0".'howKnown' => [parent::class, 'howKnown', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'joinDate' => [parent::class, 'joinDate', null, 16],
        "\0".parent::class."\0".'languages' => [parent::class, 'languages', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'motivation' => [parent::class, 'motivation', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'navigationLicenses' => [parent::class, 'navigationLicenses', null, 16],
        "\0".parent::class."\0".'otherQualifications' => [parent::class, 'otherQualifications', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'postalCode' => [parent::class, 'postalCode', null, 16],
        "\0".parent::class."\0".'previousVolunteeringInstitutions' => [parent::class, 'previousVolunteeringInstitutions', null, 16],
        "\0".parent::class."\0".'profession' => [parent::class, 'profession', null, 16],
        "\0".parent::class."\0".'profilePicture' => [parent::class, 'profilePicture', null, 16],
        "\0".parent::class."\0".'province' => [parent::class, 'province', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'specialization' => [parent::class, 'specialization', null, 16],
        "\0".parent::class."\0".'specificQualifications' => [parent::class, 'specificQualifications', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'streetType' => [parent::class, 'streetType', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'address' => [parent::class, 'address', null, 16],
        'allergies' => [parent::class, 'allergies', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'contactPerson1' => [parent::class, 'contactPerson1', null, 16],
        'contactPerson2' => [parent::class, 'contactPerson2', null, 16],
        'contactPhone1' => [parent::class, 'contactPhone1', null, 16],
        'contactPhone2' => [parent::class, 'contactPhone2', null, 16],
        'dateOfBirth' => [parent::class, 'dateOfBirth', null, 16],
        'dni' => [parent::class, 'dni', null, 16],
        'drivingLicenseExpiryDate' => [parent::class, 'drivingLicenseExpiryDate', null, 16],
        'drivingLicenses' => [parent::class, 'drivingLicenses', null, 16],
        'employmentStatus' => [parent::class, 'employmentStatus', null, 16],
        'hasVolunteeredBefore' => [parent::class, 'hasVolunteeredBefore', null, 16],
        'howKnown' => [parent::class, 'howKnown', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'joinDate' => [parent::class, 'joinDate', null, 16],
        'languages' => [parent::class, 'languages', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'motivation' => [parent::class, 'motivation', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'navigationLicenses' => [parent::class, 'navigationLicenses', null, 16],
        'otherQualifications' => [parent::class, 'otherQualifications', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'postalCode' => [parent::class, 'postalCode', null, 16],
        'previousVolunteeringInstitutions' => [parent::class, 'previousVolunteeringInstitutions', null, 16],
        'profession' => [parent::class, 'profession', null, 16],
        'profilePicture' => [parent::class, 'profilePicture', null, 16],
        'province' => [parent::class, 'province', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'specialization' => [parent::class, 'specialization', null, 16],
        'specificQualifications' => [parent::class, 'specificQualifications', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'streetType' => [parent::class, 'streetType', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
